/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class Serializer {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Serializer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Serializer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Serializer obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_Serializer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void Reset() {
    jnisecommonJNI.Serializer_Reset(swigCPtr, this);
  }

  public String GetCStr() {
    return jnisecommonJNI.Serializer_GetCStr(swigCPtr, this);
  }

  public String SerializerType() {
    return jnisecommonJNI.Serializer_SerializerType(swigCPtr, this);
  }

  public static Serializer CreateJSONSerializer(SerializationParameters params) {
    long cPtr = jnisecommonJNI.Serializer_CreateJSONSerializer(SerializationParameters.getCPtr(params), params);
    return (cPtr == 0) ? null : new Serializer(cPtr, false);
  }

}
