/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class Size {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Size(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Size obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Size obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_Size(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Size() {
    this(jnisecommonJNI.new_Size__SWIG_0(), true);
  }

  public Size(int width, int height) {
    this(jnisecommonJNI.new_Size__SWIG_1(width, height), true);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.Size_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public void setWidth(int value) {
    jnisecommonJNI.Size_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return jnisecommonJNI.Size_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    jnisecommonJNI.Size_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return jnisecommonJNI.Size_height_get(swigCPtr, this);
  }

}
