/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public final class YUVType {
  public final static YUVType YUVTYPE_UNDEFINED = new YUVType("YUVTYPE_UNDEFINED", jnisecommonJNI.YUVTYPE_UNDEFINED_get());
  public final static YUVType YUVTYPE_NV21 = new YUVType("YUVTYPE_NV21", jnisecommonJNI.YUVTYPE_NV21_get());
  public final static YUVType YUVTYPE_420_888 = new YUVType("YUVTYPE_420_888", jnisecommonJNI.YUVTYPE_420_888_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static YUVType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + YUVType.class + " with value " + swigValue);
  }

  private YUVType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private YUVType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private YUVType(String swigName, YUVType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static YUVType[] swigValues = { YUVTYPE_UNDEFINED, YUVTYPE_NV21, YUVTYPE_420_888 };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

