/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class OcrPair {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OcrPair(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OcrPair obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OcrPair obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_OcrPair(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OcrPair() {
    this(jnisecommonJNI.new_OcrPair__SWIG_0(), true);
  }

  public OcrPair(MutableString utf8_char, float confidence) {
    this(jnisecommonJNI.new_OcrPair__SWIG_1(MutableString.getCPtr(utf8_char), utf8_char, confidence), true);
  }

  public OcrPair(String utf8_char, float confidence) {
    this(jnisecommonJNI.new_OcrPair__SWIG_2(utf8_char, confidence), true);
  }

  public OcrPair(MutableString utf8_char, int confidence) {
    this(jnisecommonJNI.new_OcrPair__SWIG_3(MutableString.getCPtr(utf8_char), utf8_char, confidence), true);
  }

  public OcrPair(String utf8_char, int confidence) {
    this(jnisecommonJNI.new_OcrPair__SWIG_4(utf8_char, confidence), true);
  }

  public String GetCharacter() {
    return jnisecommonJNI.OcrPair_GetCharacter(swigCPtr, this);
  }

  public void SetCharacter(MutableString utf8_char) {
    jnisecommonJNI.OcrPair_SetCharacter__SWIG_0(swigCPtr, this, MutableString.getCPtr(utf8_char), utf8_char);
  }

  public void SetCharacter(String utf8_char) {
    jnisecommonJNI.OcrPair_SetCharacter__SWIG_1(swigCPtr, this, utf8_char);
  }

  public short GetConfidence() {
    return jnisecommonJNI.OcrPair_GetConfidence(swigCPtr, this);
  }

  public void SetConfidence(float confidence) {
    jnisecommonJNI.OcrPair_SetConfidence__SWIG_0(swigCPtr, this, confidence);
  }

  public void SetConfidence(int confidence) {
    jnisecommonJNI.OcrPair_SetConfidence__SWIG_1(swigCPtr, this, confidence);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.OcrPair_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
