//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.common {

public enum YUVType {
  YUVTYPE_UNDEFINED = 0,
  YUVTYPE_NV21 = 1,
  YUVTYPE_420_888 = 2
}

}
