/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public final class ImagePixelFormat {
  public final static ImagePixelFormat IPF_G = new ImagePixelFormat("IPF_G", jnisecommonJNI.IPF_G_get());
  public final static ImagePixelFormat IPF_GA = new ImagePixelFormat("IPF_GA");
  public final static ImagePixelFormat IPF_AG = new ImagePixelFormat("IPF_AG");
  public final static ImagePixelFormat IPF_RGB = new ImagePixelFormat("IPF_RGB");
  public final static ImagePixelFormat IPF_BGR = new ImagePixelFormat("IPF_BGR");
  public final static ImagePixelFormat IPF_BGRA = new ImagePixelFormat("IPF_BGRA");
  public final static ImagePixelFormat IPF_ARGB = new ImagePixelFormat("IPF_ARGB");
  public final static ImagePixelFormat IPF_RGBA = new ImagePixelFormat("IPF_RGBA");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static ImagePixelFormat swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + ImagePixelFormat.class + " with value " + swigValue);
  }

  private ImagePixelFormat(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private ImagePixelFormat(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private ImagePixelFormat(String swigName, ImagePixelFormat swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static ImagePixelFormat[] swigValues = { IPF_G, IPF_GA, IPF_AG, IPF_RGB, IPF_BGR, IPF_BGRA, IPF_ARGB, IPF_RGBA };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

