/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class YUVDimensions {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public YUVDimensions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(YUVDimensions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(YUVDimensions obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_YUVDimensions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public YUVDimensions() {
    this(jnisecommonJNI.new_YUVDimensions__SWIG_0(), true);
  }

  public YUVDimensions(int y_pixel_stride, int y_row_stride, int u_pixel_stride, int u_row_stride, int v_pixel_stride, int v_row_stride, int width, int height, YUVType type) {
    this(jnisecommonJNI.new_YUVDimensions__SWIG_1(y_pixel_stride, y_row_stride, u_pixel_stride, u_row_stride, v_pixel_stride, v_row_stride, width, height, type.swigValue()), true);
  }

  public void setY_plane_pixel_stride(int value) {
    jnisecommonJNI.YUVDimensions_y_plane_pixel_stride_set(swigCPtr, this, value);
  }

  public int getY_plane_pixel_stride() {
    return jnisecommonJNI.YUVDimensions_y_plane_pixel_stride_get(swigCPtr, this);
  }

  public void setY_plane_row_stride(int value) {
    jnisecommonJNI.YUVDimensions_y_plane_row_stride_set(swigCPtr, this, value);
  }

  public int getY_plane_row_stride() {
    return jnisecommonJNI.YUVDimensions_y_plane_row_stride_get(swigCPtr, this);
  }

  public void setU_plane_pixel_stride(int value) {
    jnisecommonJNI.YUVDimensions_u_plane_pixel_stride_set(swigCPtr, this, value);
  }

  public int getU_plane_pixel_stride() {
    return jnisecommonJNI.YUVDimensions_u_plane_pixel_stride_get(swigCPtr, this);
  }

  public void setU_plane_row_stride(int value) {
    jnisecommonJNI.YUVDimensions_u_plane_row_stride_set(swigCPtr, this, value);
  }

  public int getU_plane_row_stride() {
    return jnisecommonJNI.YUVDimensions_u_plane_row_stride_get(swigCPtr, this);
  }

  public void setV_plane_pixel_stride(int value) {
    jnisecommonJNI.YUVDimensions_v_plane_pixel_stride_set(swigCPtr, this, value);
  }

  public int getV_plane_pixel_stride() {
    return jnisecommonJNI.YUVDimensions_v_plane_pixel_stride_get(swigCPtr, this);
  }

  public void setV_plane_row_stride(int value) {
    jnisecommonJNI.YUVDimensions_v_plane_row_stride_set(swigCPtr, this, value);
  }

  public int getV_plane_row_stride() {
    return jnisecommonJNI.YUVDimensions_v_plane_row_stride_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    jnisecommonJNI.YUVDimensions_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return jnisecommonJNI.YUVDimensions_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    jnisecommonJNI.YUVDimensions_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return jnisecommonJNI.YUVDimensions_height_get(swigCPtr, this);
  }

  public void setType(YUVType value) {
    jnisecommonJNI.YUVDimensions_type_set(swigCPtr, this, value.swigValue());
  }

  public YUVType getType() {
    return YUVType.swigToEnum(jnisecommonJNI.YUVDimensions_type_get(swigCPtr, this));
  }

}
