/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdVideoAuthenticationSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdVideoAuthenticationSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdVideoAuthenticationSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdVideoAuthenticationSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdVideoAuthenticationSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetActivationRequest() {
    return jniidengineJNI.IdVideoAuthenticationSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jniidengineJNI.IdVideoAuthenticationSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jniidengineJNI.IdVideoAuthenticationSession_IsActivated(swigCPtr, this);
  }

  public void ProcessFrame(Image frame) {
    jniidengineJNI.IdVideoAuthenticationSession_ProcessFrame(swigCPtr, this, Image.getCPtr(frame), frame);
  }

  public void ProcessData(ByteString data) {
    jniidengineJNI.IdVideoAuthenticationSession_ProcessData(swigCPtr, this, ByteString.getCPtr(data), data);
  }

  public IdVideoAuthenticationInstruction GetCurrentInstruction() {
    return new IdVideoAuthenticationInstruction(jniidengineJNI.IdVideoAuthenticationSession_GetCurrentInstruction(swigCPtr, this), false);
  }

  public boolean HasDocumentResult() {
    return jniidengineJNI.IdVideoAuthenticationSession_HasDocumentResult(swigCPtr, this);
  }

  public IdResult GetDocumentResult() {
    return new IdResult(jniidengineJNI.IdVideoAuthenticationSession_GetDocumentResult(swigCPtr, this), false);
  }

  public boolean HasFaceMatchingResult() {
    return jniidengineJNI.IdVideoAuthenticationSession_HasFaceMatchingResult(swigCPtr, this);
  }

  public IdFaceSimilarityResult GetFaceMatchingResult() {
    return new IdFaceSimilarityResult(jniidengineJNI.IdVideoAuthenticationSession_GetFaceMatchingResult(swigCPtr, this), false);
  }

  public boolean HasFaceLivenessResult() {
    return jniidengineJNI.IdVideoAuthenticationSession_HasFaceLivenessResult(swigCPtr, this);
  }

  public IdFaceLivenessResult GetFaceLivenessResult() {
    return new IdFaceLivenessResult(jniidengineJNI.IdVideoAuthenticationSession_GetFaceLivenessResult(swigCPtr, this), false);
  }

  public IdCheckStatus GetAuthenticationStatus() {
    return IdCheckStatus.swigToEnum(jniidengineJNI.IdVideoAuthenticationSession_GetAuthenticationStatus(swigCPtr, this));
  }

  public IdVideoAuthenticationTranscript GetTranscript() {
    return new IdVideoAuthenticationTranscript(jniidengineJNI.IdVideoAuthenticationSession_GetTranscript(swigCPtr, this), false);
  }

  public void Suspend() {
    jniidengineJNI.IdVideoAuthenticationSession_Suspend(swigCPtr, this);
  }

  public void Resume() {
    jniidengineJNI.IdVideoAuthenticationSession_Resume(swigCPtr, this);
  }

  public void Reset() {
    jniidengineJNI.IdVideoAuthenticationSession_Reset(swigCPtr, this);
  }

}
