/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdAnimatedFieldsMapIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdAnimatedFieldsMapIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdAnimatedFieldsMapIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdAnimatedFieldsMapIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdAnimatedFieldsMapIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdAnimatedFieldsMapIterator(IdAnimatedFieldsMapIterator other) {
    this(jniidengineJNI.new_IdAnimatedFieldsMapIterator(IdAnimatedFieldsMapIterator.getCPtr(other), other), true);
  }

  public String GetKey() {
    return jniidengineJNI.IdAnimatedFieldsMapIterator_GetKey(swigCPtr, this);
  }

  public IdAnimatedField GetValue() {
    return new IdAnimatedField(jniidengineJNI.IdAnimatedFieldsMapIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(IdAnimatedFieldsMapIterator rvalue) {
    return jniidengineJNI.IdAnimatedFieldsMapIterator_Equals(swigCPtr, this, IdAnimatedFieldsMapIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jniidengineJNI.IdAnimatedFieldsMapIterator_Advance(swigCPtr, this);
  }

}
