/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdFieldProcessingSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdFieldProcessingSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdFieldProcessingSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdFieldProcessingSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdFieldProcessingSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetActivationRequest() {
    return jniidengineJNI.IdFieldProcessingSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jniidengineJNI.IdFieldProcessingSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jniidengineJNI.IdFieldProcessingSession_IsActivated(swigCPtr, this);
  }

  public void Process() {
    jniidengineJNI.IdFieldProcessingSession_Process(swigCPtr, this);
  }

  public int GetTextFieldsCount() {
    return jniidengineJNI.IdFieldProcessingSession_GetTextFieldsCount(swigCPtr, this);
  }

  public boolean HasTextField(String field_name) {
    return jniidengineJNI.IdFieldProcessingSession_HasTextField(swigCPtr, this, field_name);
  }

  public IdTextField GetTextField(String field_name) {
    return new IdTextField(jniidengineJNI.IdFieldProcessingSession_GetTextField(swigCPtr, this, field_name), false);
  }

  public void SetTextField(String field_name, IdTextField field) {
    jniidengineJNI.IdFieldProcessingSession_SetTextField(swigCPtr, this, field_name, IdTextField.getCPtr(field), field);
  }

  public void RemoveTextField(String field_name) {
    jniidengineJNI.IdFieldProcessingSession_RemoveTextField(swigCPtr, this, field_name);
  }

  public IdTextFieldsMapIterator TextFieldsBegin() {
    return new IdTextFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_TextFieldsBegin(swigCPtr, this), true);
  }

  public IdTextFieldsMapIterator TextFieldsEnd() {
    return new IdTextFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_TextFieldsEnd(swigCPtr, this), true);
  }

  public int GetImageFieldsCount() {
    return jniidengineJNI.IdFieldProcessingSession_GetImageFieldsCount(swigCPtr, this);
  }

  public boolean HasImageField(String field_name) {
    return jniidengineJNI.IdFieldProcessingSession_HasImageField(swigCPtr, this, field_name);
  }

  public IdImageField GetImageField(String field_name) {
    return new IdImageField(jniidengineJNI.IdFieldProcessingSession_GetImageField(swigCPtr, this, field_name), false);
  }

  public void SetImageField(String field_name, IdImageField field) {
    jniidengineJNI.IdFieldProcessingSession_SetImageField(swigCPtr, this, field_name, IdImageField.getCPtr(field), field);
  }

  public void RemoveImageField(String field_name) {
    jniidengineJNI.IdFieldProcessingSession_RemoveImageField(swigCPtr, this, field_name);
  }

  public IdImageFieldsMapIterator ImageFieldsBegin() {
    return new IdImageFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_ImageFieldsBegin(swigCPtr, this), true);
  }

  public IdImageFieldsMapIterator ImageFieldsEnd() {
    return new IdImageFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_ImageFieldsEnd(swigCPtr, this), true);
  }

  public int GetAnimatedFieldsCount() {
    return jniidengineJNI.IdFieldProcessingSession_GetAnimatedFieldsCount(swigCPtr, this);
  }

  public boolean HasAnimatedField(String field_name) {
    return jniidengineJNI.IdFieldProcessingSession_HasAnimatedField(swigCPtr, this, field_name);
  }

  public IdAnimatedField GetAnimatedField(String field_name) {
    return new IdAnimatedField(jniidengineJNI.IdFieldProcessingSession_GetAnimatedField(swigCPtr, this, field_name), false);
  }

  public void SetAnimatedField(String field_name, IdAnimatedField field) {
    jniidengineJNI.IdFieldProcessingSession_SetAnimatedField(swigCPtr, this, field_name, IdAnimatedField.getCPtr(field), field);
  }

  public void RemoveAnimatedField(String field_name) {
    jniidengineJNI.IdFieldProcessingSession_RemoveAnimatedField(swigCPtr, this, field_name);
  }

  public IdAnimatedFieldsMapIterator AnimatedFieldsBegin() {
    return new IdAnimatedFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_AnimatedFieldsBegin(swigCPtr, this), true);
  }

  public IdAnimatedFieldsMapIterator AnimatedFieldsEnd() {
    return new IdAnimatedFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_AnimatedFieldsEnd(swigCPtr, this), true);
  }

  public int GetCheckFieldsCount() {
    return jniidengineJNI.IdFieldProcessingSession_GetCheckFieldsCount(swigCPtr, this);
  }

  public boolean HasCheckField(String field_name) {
    return jniidengineJNI.IdFieldProcessingSession_HasCheckField(swigCPtr, this, field_name);
  }

  public IdCheckField GetCheckField(String field_name) {
    return new IdCheckField(jniidengineJNI.IdFieldProcessingSession_GetCheckField(swigCPtr, this, field_name), false);
  }

  public void SetCheckField(String field_name, IdCheckField field) {
    jniidengineJNI.IdFieldProcessingSession_SetCheckField(swigCPtr, this, field_name, IdCheckField.getCPtr(field), field);
  }

  public void RemoveCheckField(String field_name) {
    jniidengineJNI.IdFieldProcessingSession_RemoveCheckField(swigCPtr, this, field_name);
  }

  public IdCheckFieldsMapIterator CheckFieldsBegin() {
    return new IdCheckFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_CheckFieldsBegin(swigCPtr, this), true);
  }

  public IdCheckFieldsMapIterator CheckFieldsEnd() {
    return new IdCheckFieldsMapIterator(jniidengineJNI.IdFieldProcessingSession_CheckFieldsEnd(swigCPtr, this), true);
  }

  public void Reset() {
    jniidengineJNI.IdFieldProcessingSession_Reset(swigCPtr, this);
  }

}
