/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdVideoAuthenticationInstruction {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdVideoAuthenticationInstruction(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdVideoAuthenticationInstruction obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdVideoAuthenticationInstruction obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdVideoAuthenticationInstruction(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdVideoAuthenticationInstruction(int frame_index, String code) {
    this(jniidengineJNI.new_IdVideoAuthenticationInstruction__SWIG_0(frame_index, code), true);
  }

  public IdVideoAuthenticationInstruction(IdVideoAuthenticationInstruction copy) {
    this(jniidengineJNI.new_IdVideoAuthenticationInstruction__SWIG_1(IdVideoAuthenticationInstruction.getCPtr(copy), copy), true);
  }

  public int GetFrameIndex() {
    return jniidengineJNI.IdVideoAuthenticationInstruction_GetFrameIndex(swigCPtr, this);
  }

  public void SetFrameIndex(int frame_index) {
    jniidengineJNI.IdVideoAuthenticationInstruction_SetFrameIndex(swigCPtr, this, frame_index);
  }

  public String GetInstructionCode() {
    return jniidengineJNI.IdVideoAuthenticationInstruction_GetInstructionCode(swigCPtr, this);
  }

  public void SetInstructionCode(String code) {
    jniidengineJNI.IdVideoAuthenticationInstruction_SetInstructionCode(swigCPtr, this, code);
  }

  public int GetParametersCount() {
    return jniidengineJNI.IdVideoAuthenticationInstruction_GetParametersCount(swigCPtr, this);
  }

  public String GetParameter(String par_name) {
    return jniidengineJNI.IdVideoAuthenticationInstruction_GetParameter(swigCPtr, this, par_name);
  }

  public boolean HasParameter(String par_name) {
    return jniidengineJNI.IdVideoAuthenticationInstruction_HasParameter(swigCPtr, this, par_name);
  }

  public void SetParameter(String par_name, String par_value) {
    jniidengineJNI.IdVideoAuthenticationInstruction_SetParameter(swigCPtr, this, par_name, par_value);
  }

  public void RemoveParameter(String par_name) {
    jniidengineJNI.IdVideoAuthenticationInstruction_RemoveParameter(swigCPtr, this, par_name);
  }

  public StringsMapIterator ParametersBegin() {
    return new StringsMapIterator(jniidengineJNI.IdVideoAuthenticationInstruction_ParametersBegin(swigCPtr, this), true);
  }

  public StringsMapIterator ParametersEnd() {
    return new StringsMapIterator(jniidengineJNI.IdVideoAuthenticationInstruction_ParametersEnd(swigCPtr, this), true);
  }

}
