/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdOslPad {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdOslPad(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdOslPad obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdOslPad obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdOslPad(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setName(IdOslPadName value) {
    jniidengineJNI.IdOslPad_name_set(swigCPtr, this, value.swigValue());
  }

  public IdOslPadName getName() {
    return IdOslPadName.swigToEnum(jniidengineJNI.IdOslPad_name_get(swigCPtr, this));
  }

  public void setVerdict(IdOslPadVerdict value) {
    jniidengineJNI.IdOslPad_verdict_set(swigCPtr, this, value.swigValue());
  }

  public IdOslPadVerdict getVerdict() {
    return IdOslPadVerdict.swigToEnum(jniidengineJNI.IdOslPad_verdict_get(swigCPtr, this));
  }

  public IdOslPad() {
    this(jniidengineJNI.new_IdOslPad(), true);
  }

}
