/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

public final class IdOslPadVerdict {
  public final static IdOslPadVerdict NotDetected = new IdOslPadVerdict("NotDetected");
  public final static IdOslPadVerdict NotRun = new IdOslPadVerdict("NotRun");
  public final static IdOslPadVerdict Detected = new IdOslPadVerdict("Detected");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IdOslPadVerdict swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IdOslPadVerdict.class + " with value " + swigValue);
  }

  private IdOslPadVerdict(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IdOslPadVerdict(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IdOslPadVerdict(String swigName, IdOslPadVerdict swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IdOslPadVerdict[] swigValues = { NotDetected, NotRun, Detected };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

