/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdVideoAuthenticationTranscript {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdVideoAuthenticationTranscript(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdVideoAuthenticationTranscript obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdVideoAuthenticationTranscript obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdVideoAuthenticationTranscript(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdVideoAuthenticationTranscript(IdVideoAuthenticationInstruction initial_instruction) {
    this(jniidengineJNI.new_IdVideoAuthenticationTranscript__SWIG_0(IdVideoAuthenticationInstruction.getCPtr(initial_instruction), initial_instruction), true);
  }

  public IdVideoAuthenticationTranscript(IdVideoAuthenticationTranscript copy) {
    this(jniidengineJNI.new_IdVideoAuthenticationTranscript__SWIG_1(IdVideoAuthenticationTranscript.getCPtr(copy), copy), true);
  }

  public int GetFrameInfosCount() {
    return jniidengineJNI.IdVideoAuthenticationTranscript_GetFrameInfosCount(swigCPtr, this);
  }

  public IdVideoAuthenticationFrameInfo GetFrameInfo(int index) {
    return new IdVideoAuthenticationFrameInfo(jniidengineJNI.IdVideoAuthenticationTranscript_GetFrameInfo(swigCPtr, this, index), false);
  }

  public IdVideoAuthenticationFrameInfo GetMutableFrameInfo(int index) {
    return new IdVideoAuthenticationFrameInfo(jniidengineJNI.IdVideoAuthenticationTranscript_GetMutableFrameInfo(swigCPtr, this, index), false);
  }

  public void AppendFrameInfo(IdVideoAuthenticationFrameInfo frame_info) {
    jniidengineJNI.IdVideoAuthenticationTranscript_AppendFrameInfo(swigCPtr, this, IdVideoAuthenticationFrameInfo.getCPtr(frame_info), frame_info);
  }

  public void SetFrameInfo(int index, IdVideoAuthenticationFrameInfo frame_info) {
    jniidengineJNI.IdVideoAuthenticationTranscript_SetFrameInfo(swigCPtr, this, index, IdVideoAuthenticationFrameInfo.getCPtr(frame_info), frame_info);
  }

  public void ResizeFrameInfosContainer(int size) {
    jniidengineJNI.IdVideoAuthenticationTranscript_ResizeFrameInfosContainer(swigCPtr, this, size);
  }

  public int GetInstructionsCount() {
    return jniidengineJNI.IdVideoAuthenticationTranscript_GetInstructionsCount(swigCPtr, this);
  }

  public IdVideoAuthenticationInstruction GetInstruction(int index) {
    return new IdVideoAuthenticationInstruction(jniidengineJNI.IdVideoAuthenticationTranscript_GetInstruction(swigCPtr, this, index), false);
  }

  public IdVideoAuthenticationInstruction GetMutableInstruction(int index) {
    return new IdVideoAuthenticationInstruction(jniidengineJNI.IdVideoAuthenticationTranscript_GetMutableInstruction(swigCPtr, this, index), false);
  }

  public void AppendInstruction(IdVideoAuthenticationInstruction instruction) {
    jniidengineJNI.IdVideoAuthenticationTranscript_AppendInstruction(swigCPtr, this, IdVideoAuthenticationInstruction.getCPtr(instruction), instruction);
  }

  public void SetInstruction(int index, IdVideoAuthenticationInstruction instruction) {
    jniidengineJNI.IdVideoAuthenticationTranscript_SetInstruction(swigCPtr, this, index, IdVideoAuthenticationInstruction.getCPtr(instruction), instruction);
  }

  public void ResizeInstructionsContainer(int size) {
    jniidengineJNI.IdVideoAuthenticationTranscript_ResizeInstructionsContainer(swigCPtr, this, size);
  }

  public int GetAnomaliesCount() {
    return jniidengineJNI.IdVideoAuthenticationTranscript_GetAnomaliesCount(swigCPtr, this);
  }

  public IdVideoAuthenticationAnomaly GetAnomaly(int index) {
    return new IdVideoAuthenticationAnomaly(jniidengineJNI.IdVideoAuthenticationTranscript_GetAnomaly(swigCPtr, this, index), false);
  }

  public IdVideoAuthenticationAnomaly GetMutableAnomaly(int index) {
    return new IdVideoAuthenticationAnomaly(jniidengineJNI.IdVideoAuthenticationTranscript_GetMutableAnomaly(swigCPtr, this, index), false);
  }

  public void AppendAnomaly(IdVideoAuthenticationAnomaly anomaly) {
    jniidengineJNI.IdVideoAuthenticationTranscript_AppendAnomaly(swigCPtr, this, IdVideoAuthenticationAnomaly.getCPtr(anomaly), anomaly);
  }

  public void SetAnomaly(int index, IdVideoAuthenticationAnomaly anomaly) {
    jniidengineJNI.IdVideoAuthenticationTranscript_SetAnomaly(swigCPtr, this, index, IdVideoAuthenticationAnomaly.getCPtr(anomaly), anomaly);
  }

  public void ResizeAnomaliesContainer(int size) {
    jniidengineJNI.IdVideoAuthenticationTranscript_ResizeAnomaliesContainer(swigCPtr, this, size);
  }

  public IdVideoAuthenticationInstruction GetCurrentInstruction() {
    return new IdVideoAuthenticationInstruction(jniidengineJNI.IdVideoAuthenticationTranscript_GetCurrentInstruction(swigCPtr, this), false);
  }

  public IdVideoAuthenticationInstruction GetMutableCurrentInstruction() {
    return new IdVideoAuthenticationInstruction(jniidengineJNI.IdVideoAuthenticationTranscript_GetMutableCurrentInstruction(swigCPtr, this), false);
  }

  public void SetCurrentInstruction(IdVideoAuthenticationInstruction instruction) {
    jniidengineJNI.IdVideoAuthenticationTranscript_SetCurrentInstruction(swigCPtr, this, IdVideoAuthenticationInstruction.getCPtr(instruction), instruction);
  }

}
