/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class Polygon {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Polygon(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Polygon obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Polygon obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_Polygon(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Polygon() {
    this(jnisecommonJNI.new_Polygon__SWIG_0(), true);
  }

  public Polygon(Point points, int points_count) {
    this(jnisecommonJNI.new_Polygon__SWIG_1(Point.getCPtr(points), points, points_count), true);
  }

  public Polygon(Polygon other) {
    this(jnisecommonJNI.new_Polygon__SWIG_2(Polygon.getCPtr(other), other), true);
  }

  public int GetPointsCount() {
    return jnisecommonJNI.Polygon_GetPointsCount(swigCPtr, this);
  }

  public Point GetPoints() {
    long cPtr = jnisecommonJNI.Polygon_GetPoints(swigCPtr, this);
    return (cPtr == 0) ? null : new Point(cPtr, false);
  }

  public Point GetPoint(int index) {
    return new Point(jnisecommonJNI.Polygon_GetPoint(swigCPtr, this, index), false);
  }

  public Point GetMutablePoint(int index) {
    return new Point(jnisecommonJNI.Polygon_GetMutablePoint(swigCPtr, this, index), false);
  }

  public void SetPoint(int index, Point p) {
    jnisecommonJNI.Polygon_SetPoint(swigCPtr, this, index, Point.getCPtr(p), p);
  }

  public void Resize(int size) {
    jnisecommonJNI.Polygon_Resize(swigCPtr, this, size);
  }

  public Rectangle GetBoundingRectangle() {
    return new Rectangle(jnisecommonJNI.Polygon_GetBoundingRectangle(swigCPtr, this), true);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.Polygon_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
