/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdImageField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdImageField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdImageField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdImageField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdImageField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdImageField() {
    this(jniidengineJNI.new_IdImageField__SWIG_0(), true);
  }

  public IdImageField(String name, Image value, boolean is_accepted, double confidence) {
    this(jniidengineJNI.new_IdImageField__SWIG_1(name, Image.getCPtr(value), value, is_accepted, confidence), true);
  }

  public IdImageField(String name, Image value, boolean is_accepted) {
    this(jniidengineJNI.new_IdImageField__SWIG_2(name, Image.getCPtr(value), value, is_accepted), true);
  }

  public IdImageField(String name, Image value) {
    this(jniidengineJNI.new_IdImageField__SWIG_3(name, Image.getCPtr(value), value), true);
  }

  public IdImageField(IdImageField copy) {
    this(jniidengineJNI.new_IdImageField__SWIG_4(IdImageField.getCPtr(copy), copy), true);
  }

  public String GetName() {
    return jniidengineJNI.IdImageField_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniidengineJNI.IdImageField_SetName(swigCPtr, this, name);
  }

  public Image GetValue() {
    return new Image(jniidengineJNI.IdImageField_GetValue(swigCPtr, this), false);
  }

  public void SetValue(Image value) {
    jniidengineJNI.IdImageField_SetValue(swigCPtr, this, Image.getCPtr(value), value);
  }

  public IdBaseFieldInfo GetBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdImageField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public IdBaseFieldInfo GetMutableBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdImageField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

}
