/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

public final class IdFaceSimilarity {
  public final static IdFaceSimilarity Different = new IdFaceSimilarity("Different");
  public final static IdFaceSimilarity Uncertain = new IdFaceSimilarity("Uncertain");
  public final static IdFaceSimilarity Same = new IdFaceSimilarity("Same");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IdFaceSimilarity swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IdFaceSimilarity.class + " with value " + swigValue);
  }

  private IdFaceSimilarity(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IdFaceSimilarity(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IdFaceSimilarity(String swigName, IdFaceSimilarity swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IdFaceSimilarity[] swigValues = { Different, Uncertain, Same };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

