/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

public final class IdCheckStatus {
  public final static IdCheckStatus IdCheckStatus_Undefined = new IdCheckStatus("IdCheckStatus_Undefined");
  public final static IdCheckStatus IdCheckStatus_Passed = new IdCheckStatus("IdCheckStatus_Passed");
  public final static IdCheckStatus IdCheckStatus_Failed = new IdCheckStatus("IdCheckStatus_Failed");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IdCheckStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IdCheckStatus.class + " with value " + swigValue);
  }

  private IdCheckStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IdCheckStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IdCheckStatus(String swigName, IdCheckStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IdCheckStatus[] swigValues = { IdCheckStatus_Undefined, IdCheckStatus_Passed, IdCheckStatus_Failed };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

