/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdAnimatedField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdAnimatedField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdAnimatedField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdAnimatedField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdAnimatedField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdAnimatedField() {
    this(jniidengineJNI.new_IdAnimatedField__SWIG_0(), true);
  }

  public IdAnimatedField(String name, boolean is_accepted, double confidence) {
    this(jniidengineJNI.new_IdAnimatedField__SWIG_1(name, is_accepted, confidence), true);
  }

  public IdAnimatedField(String name, boolean is_accepted) {
    this(jniidengineJNI.new_IdAnimatedField__SWIG_2(name, is_accepted), true);
  }

  public IdAnimatedField(String name) {
    this(jniidengineJNI.new_IdAnimatedField__SWIG_3(name), true);
  }

  public IdAnimatedField(IdAnimatedField copy) {
    this(jniidengineJNI.new_IdAnimatedField__SWIG_4(IdAnimatedField.getCPtr(copy), copy), true);
  }

  public String GetName() {
    return jniidengineJNI.IdAnimatedField_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniidengineJNI.IdAnimatedField_SetName(swigCPtr, this, name);
  }

  public int GetFramesCount() {
    return jniidengineJNI.IdAnimatedField_GetFramesCount(swigCPtr, this);
  }

  public Image GetFrame(int frame_id) {
    return new Image(jniidengineJNI.IdAnimatedField_GetFrame(swigCPtr, this, frame_id), false);
  }

  public void AppendFrame(Image frame) {
    jniidengineJNI.IdAnimatedField_AppendFrame(swigCPtr, this, Image.getCPtr(frame), frame);
  }

  public void ClearFrames() {
    jniidengineJNI.IdAnimatedField_ClearFrames(swigCPtr, this);
  }

  public IdBaseFieldInfo GetBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdAnimatedField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public IdBaseFieldInfo GetMutableBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdAnimatedField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

}
