/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdFaceSession {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdFaceSession(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdFaceSession obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdFaceSession obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdFaceSession(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String GetActivationRequest() {
    return jniidengineJNI.IdFaceSession_GetActivationRequest(swigCPtr, this);
  }

  public void Activate(String activation_response) {
    jniidengineJNI.IdFaceSession_Activate(swigCPtr, this, activation_response);
  }

  public boolean IsActivated() {
    return jniidengineJNI.IdFaceSession_IsActivated(swigCPtr, this);
  }

  public IdFaceSimilarityResult GetSimilarity(Image face_image_a, Image face_image_b) {
    return new IdFaceSimilarityResult(jniidengineJNI.IdFaceSession_GetSimilarity(swigCPtr, this, Image.getCPtr(face_image_a), face_image_a, Image.getCPtr(face_image_b), face_image_b), true);
  }

  public IdFaceSimilarityResult GetSimilarityWith(Image compare_image) {
    return new IdFaceSimilarityResult(jniidengineJNI.IdFaceSession_GetSimilarityWith(swigCPtr, this, Image.getCPtr(compare_image), compare_image), true);
  }

  public void AddFaceImage(Image face_image) {
    jniidengineJNI.IdFaceSession_AddFaceImage(swigCPtr, this, Image.getCPtr(face_image), face_image);
  }

  public void SetFaceToMatchWith(Image face_image) {
    jniidengineJNI.IdFaceSession_SetFaceToMatchWith(swigCPtr, this, Image.getCPtr(face_image), face_image);
  }

  public IdFaceRectsResult GetRects(Image image) {
    return new IdFaceRectsResult(jniidengineJNI.IdFaceSession_GetRects(swigCPtr, this, Image.getCPtr(image), image), true);
  }

  public boolean HasAccumulatedImage() {
    return jniidengineJNI.IdFaceSession_HasAccumulatedImage(swigCPtr, this);
  }

  public IdFaceLivenessResult GetLivenessResult() {
    return new IdFaceLivenessResult(jniidengineJNI.IdFaceSession_GetLivenessResult(swigCPtr, this), true);
  }

  public long GetInstructionsCount() {
    return jniidengineJNI.IdFaceSession_GetInstructionsCount(swigCPtr, this);
  }

  public long GetPushedImagesCount() {
    return jniidengineJNI.IdFaceSession_GetPushedImagesCount(swigCPtr, this);
  }

  public long GetAllowedNumberOfFailedInstructions() {
    return jniidengineJNI.IdFaceSession_GetAllowedNumberOfFailedInstructions(swigCPtr, this);
  }

  public long GetInitializerInstructionTime() {
    return jniidengineJNI.IdFaceSession_GetInitializerInstructionTime(swigCPtr, this);
  }

  public long GetPassAllInstruction() {
    return jniidengineJNI.IdFaceSession_GetPassAllInstruction(swigCPtr, this);
  }

  public void Reset() {
    jniidengineJNI.IdFaceSession_Reset(swigCPtr, this);
  }

}
