/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdOslResult {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdOslResult(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdOslResult obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdOslResult obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdOslResult(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdOslResult() {
    this(jniidengineJNI.new_IdOslResult__SWIG_0(), true);
  }

  public IdOslResult(IdOslResult copy) {
    this(jniidengineJNI.new_IdOslResult__SWIG_1(IdOslResult.getCPtr(copy), copy), true);
  }

  public boolean GetVerdict() {
    return jniidengineJNI.IdOslResult_GetVerdict(swigCPtr, this);
  }

  public void SetVerdict(boolean verdict) {
    jniidengineJNI.IdOslResult_SetVerdict(swigCPtr, this, verdict);
  }

  public void PushPad(IdOslPad pad) {
    jniidengineJNI.IdOslResult_PushPad(swigCPtr, this, IdOslPad.getCPtr(pad), pad);
  }

  public void Clear() {
    jniidengineJNI.IdOslResult_Clear(swigCPtr, this);
  }

  public int Size() {
    return jniidengineJNI.IdOslResult_Size(swigCPtr, this);
  }

  public IdOslPadIterator OslPadBegin() {
    return new IdOslPadIterator(jniidengineJNI.IdOslResult_OslPadBegin(swigCPtr, this), true);
  }

  public IdOslPadIterator OslPadEnd() {
    return new IdOslPadIterator(jniidengineJNI.IdOslResult_OslPadEnd(swigCPtr, this), true);
  }

}
