/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdOslPadIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdOslPadIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdOslPadIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdOslPadIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdOslPadIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdOslPadIterator(IdOslPadIterator other) {
    this(jniidengineJNI.new_IdOslPadIterator(IdOslPadIterator.getCPtr(other), other), true);
  }

  public IdOslPad GetValue() {
    return new IdOslPad(jniidengineJNI.IdOslPadIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(IdOslPadIterator rvalue) {
    return jniidengineJNI.IdOslPadIterator_Equals(swigCPtr, this, IdOslPadIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jniidengineJNI.IdOslPadIterator_Advance(swigCPtr, this);
  }

}
