/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdTextField {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdTextField(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdTextField obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdTextField obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdTextField(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdTextField() {
    this(jniidengineJNI.new_IdTextField__SWIG_0(), true);
  }

  public IdTextField(String name, OcrString value, boolean is_accepted, double confidence) {
    this(jniidengineJNI.new_IdTextField__SWIG_1(name, OcrString.getCPtr(value), value, is_accepted, confidence), true);
  }

  public IdTextField(String name, OcrString value, boolean is_accepted) {
    this(jniidengineJNI.new_IdTextField__SWIG_2(name, OcrString.getCPtr(value), value, is_accepted), true);
  }

  public IdTextField(String name, OcrString value) {
    this(jniidengineJNI.new_IdTextField__SWIG_3(name, OcrString.getCPtr(value), value), true);
  }

  public IdTextField(String name, String value, boolean is_accepted, double confidence) {
    this(jniidengineJNI.new_IdTextField__SWIG_4(name, value, is_accepted, confidence), true);
  }

  public IdTextField(String name, String value, boolean is_accepted) {
    this(jniidengineJNI.new_IdTextField__SWIG_5(name, value, is_accepted), true);
  }

  public IdTextField(String name, String value) {
    this(jniidengineJNI.new_IdTextField__SWIG_6(name, value), true);
  }

  public IdTextField(IdTextField copy) {
    this(jniidengineJNI.new_IdTextField__SWIG_7(IdTextField.getCPtr(copy), copy), true);
  }

  public String GetName() {
    return jniidengineJNI.IdTextField_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniidengineJNI.IdTextField_SetName(swigCPtr, this, name);
  }

  public OcrString GetValue() {
    return new OcrString(jniidengineJNI.IdTextField_GetValue(swigCPtr, this), false);
  }

  public void SetValue(OcrString value) {
    jniidengineJNI.IdTextField_SetValue__SWIG_0(swigCPtr, this, OcrString.getCPtr(value), value);
  }

  public void SetValue(String value) {
    jniidengineJNI.IdTextField_SetValue__SWIG_1(swigCPtr, this, value);
  }

  public IdBaseFieldInfo GetBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdTextField_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public IdBaseFieldInfo GetMutableBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdTextField_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

}
