/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class Rectangle {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Rectangle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Rectangle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Rectangle obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_Rectangle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Rectangle() {
    this(jnisecommonJNI.new_Rectangle__SWIG_0(), true);
  }

  public Rectangle(int x, int y, int width, int height) {
    this(jnisecommonJNI.new_Rectangle__SWIG_1(x, y, width, height), true);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.Rectangle_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public void setX(int value) {
    jnisecommonJNI.Rectangle_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return jnisecommonJNI.Rectangle_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    jnisecommonJNI.Rectangle_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return jnisecommonJNI.Rectangle_y_get(swigCPtr, this);
  }

  public void setWidth(int value) {
    jnisecommonJNI.Rectangle_width_set(swigCPtr, this, value);
  }

  public int getWidth() {
    return jnisecommonJNI.Rectangle_width_get(swigCPtr, this);
  }

  public void setHeight(int value) {
    jnisecommonJNI.Rectangle_height_set(swigCPtr, this, value);
  }

  public int getHeight() {
    return jnisecommonJNI.Rectangle_height_get(swigCPtr, this);
  }

}
