/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class OcrChar {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public OcrChar(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(OcrChar obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(OcrChar obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_OcrChar(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public OcrChar() {
    this(jnisecommonJNI.new_OcrChar__SWIG_0(), true);
  }

  public OcrChar(OcrCharVariant variants, int variants_count, boolean is_highlighted, Quadrangle quad) {
    this(jnisecommonJNI.new_OcrChar__SWIG_1(OcrCharVariant.getCPtr(variants), variants, variants_count, is_highlighted, Quadrangle.getCPtr(quad), quad), true);
  }

  public OcrChar(OcrChar other) {
    this(jnisecommonJNI.new_OcrChar__SWIG_2(OcrChar.getCPtr(other), other), true);
  }

  public int GetVariantsCount() {
    return jnisecommonJNI.OcrChar_GetVariantsCount(swigCPtr, this);
  }

  public OcrCharVariant GetVariants() {
    long cPtr = jnisecommonJNI.OcrChar_GetVariants(swigCPtr, this);
    return (cPtr == 0) ? null : new OcrCharVariant(cPtr, false);
  }

  public OcrCharVariant GetVariant(int index) {
    return new OcrCharVariant(jnisecommonJNI.OcrChar_GetVariant(swigCPtr, this, index), false);
  }

  public OcrCharVariant GetMutableVariant(int index) {
    return new OcrCharVariant(jnisecommonJNI.OcrChar_GetMutableVariant(swigCPtr, this, index), false);
  }

  public void SetVariant(int index, OcrCharVariant v) {
    jnisecommonJNI.OcrChar_SetVariant(swigCPtr, this, index, OcrCharVariant.getCPtr(v), v);
  }

  public void Resize(int size) {
    jnisecommonJNI.OcrChar_Resize(swigCPtr, this, size);
  }

  public boolean GetIsHighlighted() {
    return jnisecommonJNI.OcrChar_GetIsHighlighted(swigCPtr, this);
  }

  public void SetIsHighlighted(boolean is_highlighted) {
    jnisecommonJNI.OcrChar_SetIsHighlighted(swigCPtr, this, is_highlighted);
  }

  public Quadrangle GetQuadrangle() {
    return new Quadrangle(jnisecommonJNI.OcrChar_GetQuadrangle(swigCPtr, this), false);
  }

  public Quadrangle GetMutableQuadrangle() {
    return new Quadrangle(jnisecommonJNI.OcrChar_GetMutableQuadrangle(swigCPtr, this), false);
  }

  public void SetQuadrangle(Quadrangle quad) {
    jnisecommonJNI.OcrChar_SetQuadrangle(swigCPtr, this, Quadrangle.getCPtr(quad), quad);
  }

  public void SortVariants() {
    jnisecommonJNI.OcrChar_SortVariants(swigCPtr, this);
  }

  public OcrCharVariant GetFirstVariant() {
    return new OcrCharVariant(jnisecommonJNI.OcrChar_GetFirstVariant(swigCPtr, this), false);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.OcrChar_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

}
