/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class RectanglesVectorIterator {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public RectanglesVectorIterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(RectanglesVectorIterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(RectanglesVectorIterator obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_RectanglesVectorIterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public RectanglesVectorIterator(RectanglesVectorIterator other) {
    this(jnisecommonJNI.new_RectanglesVectorIterator(RectanglesVectorIterator.getCPtr(other), other), true);
  }

  public Rectangle GetValue() {
    return new Rectangle(jnisecommonJNI.RectanglesVectorIterator_GetValue(swigCPtr, this), false);
  }

  public boolean Equals(RectanglesVectorIterator rvalue) {
    return jnisecommonJNI.RectanglesVectorIterator_Equals(swigCPtr, this, RectanglesVectorIterator.getCPtr(rvalue), rvalue);
  }

  public void Advance() {
    jnisecommonJNI.RectanglesVectorIterator_Advance(swigCPtr, this);
  }

}
