/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.common;

public class Point {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public Point(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(Point obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jnisecommonJNI.delete_Point(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point() {
    this(jnisecommonJNI.new_Point__SWIG_0(), true);
  }

  public Point(double x, double y) {
    this(jnisecommonJNI.new_Point__SWIG_1(x, y), true);
  }

  public void Serialize(Serializer serializer) {
    jnisecommonJNI.Point_Serialize(swigCPtr, this, Serializer.getCPtr(serializer), serializer);
  }

  public void setX(double value) {
    jnisecommonJNI.Point_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return jnisecommonJNI.Point_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    jnisecommonJNI.Point_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return jnisecommonJNI.Point_y_get(swigCPtr, this);
  }

}
