/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdFieldProcessingSessionSettings {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdFieldProcessingSessionSettings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdFieldProcessingSessionSettings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdFieldProcessingSessionSettings obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdFieldProcessingSessionSettings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdFieldProcessingSessionSettings Clone() {
    long cPtr = jniidengineJNI.IdFieldProcessingSessionSettings_Clone(swigCPtr, this);
    return (cPtr == 0) ? null : new IdFieldProcessingSessionSettings(cPtr, true);
  }

  public int GetSupportedFieldProcessorsCount() {
    return jniidengineJNI.IdFieldProcessingSessionSettings_GetSupportedFieldProcessorsCount(swigCPtr, this);
  }

  public boolean HasSupportedFieldProcessor(String field_processor_name) {
    return jniidengineJNI.IdFieldProcessingSessionSettings_HasSupportedFieldProcessor(swigCPtr, this, field_processor_name);
  }

  public StringsSetIterator SupportedFieldProcessorsBegin() {
    return new StringsSetIterator(jniidengineJNI.IdFieldProcessingSessionSettings_SupportedFieldProcessorsBegin(swigCPtr, this), true);
  }

  public StringsSetIterator SupportedFieldProcessorsEnd() {
    return new StringsSetIterator(jniidengineJNI.IdFieldProcessingSessionSettings_SupportedFieldProcessorsEnd(swigCPtr, this), true);
  }

  public String GetCurrentFieldProcessor() {
    return jniidengineJNI.IdFieldProcessingSessionSettings_GetCurrentFieldProcessor(swigCPtr, this);
  }

  public void SetCurrentFieldProcessor(String field_processor_name) {
    jniidengineJNI.IdFieldProcessingSessionSettings_SetCurrentFieldProcessor(swigCPtr, this, field_processor_name);
  }

  public int GetOptionsCount() {
    return jniidengineJNI.IdFieldProcessingSessionSettings_GetOptionsCount(swigCPtr, this);
  }

  public String GetOption(String option_name) {
    return jniidengineJNI.IdFieldProcessingSessionSettings_GetOption(swigCPtr, this, option_name);
  }

  public boolean HasOption(String option_name) {
    return jniidengineJNI.IdFieldProcessingSessionSettings_HasOption(swigCPtr, this, option_name);
  }

  public void SetOption(String option_name, String option_value) {
    jniidengineJNI.IdFieldProcessingSessionSettings_SetOption(swigCPtr, this, option_name, option_value);
  }

  public void RemoveOption(String option_name) {
    jniidengineJNI.IdFieldProcessingSessionSettings_RemoveOption(swigCPtr, this, option_name);
  }

  public StringsMapIterator OptionsBegin() {
    return new StringsMapIterator(jniidengineJNI.IdFieldProcessingSessionSettings_OptionsBegin(swigCPtr, this), true);
  }

  public StringsMapIterator OptionsEnd() {
    return new StringsMapIterator(jniidengineJNI.IdFieldProcessingSessionSettings_OptionsEnd(swigCPtr, this), true);
  }

}
