/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

import com.smartengines.common.*;

public class IdVideoAuthenticationAnomaly {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  public IdVideoAuthenticationAnomaly(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(IdVideoAuthenticationAnomaly obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public static long swigRelease(IdVideoAuthenticationAnomaly obj) {
    long ptr = 0;
    if (obj != null) {
      if (!obj.swigCMemOwn)
        throw new RuntimeException("Cannot release ownership as memory is not owned");
      ptr = obj.swigCPtr;
      obj.swigCMemOwn = false;
      obj.delete();
    }
    return ptr;
  }

  @SuppressWarnings("deprecation")
  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        jniidengineJNI.delete_IdVideoAuthenticationAnomaly(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IdVideoAuthenticationAnomaly(String name, int start_frame, int end_frame, boolean is_accepted, double confidence) {
    this(jniidengineJNI.new_IdVideoAuthenticationAnomaly__SWIG_0(name, start_frame, end_frame, is_accepted, confidence), true);
  }

  public IdVideoAuthenticationAnomaly(String name, int start_frame, int end_frame, boolean is_accepted) {
    this(jniidengineJNI.new_IdVideoAuthenticationAnomaly__SWIG_1(name, start_frame, end_frame, is_accepted), true);
  }

  public IdVideoAuthenticationAnomaly(String name, int start_frame, int end_frame) {
    this(jniidengineJNI.new_IdVideoAuthenticationAnomaly__SWIG_2(name, start_frame, end_frame), true);
  }

  public IdVideoAuthenticationAnomaly(IdVideoAuthenticationAnomaly copy) {
    this(jniidengineJNI.new_IdVideoAuthenticationAnomaly__SWIG_3(IdVideoAuthenticationAnomaly.getCPtr(copy), copy), true);
  }

  public String GetName() {
    return jniidengineJNI.IdVideoAuthenticationAnomaly_GetName(swigCPtr, this);
  }

  public void SetName(String name) {
    jniidengineJNI.IdVideoAuthenticationAnomaly_SetName(swigCPtr, this, name);
  }

  public int GetStartFrame() {
    return jniidengineJNI.IdVideoAuthenticationAnomaly_GetStartFrame(swigCPtr, this);
  }

  public void SetStartFrame(int start_frame) {
    jniidengineJNI.IdVideoAuthenticationAnomaly_SetStartFrame(swigCPtr, this, start_frame);
  }

  public int GetEndFrame() {
    return jniidengineJNI.IdVideoAuthenticationAnomaly_GetEndFrame(swigCPtr, this);
  }

  public void SetEndFrame(int end_frame) {
    jniidengineJNI.IdVideoAuthenticationAnomaly_SetEndFrame(swigCPtr, this, end_frame);
  }

  public IdBaseFieldInfo GetBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdVideoAuthenticationAnomaly_GetBaseFieldInfo(swigCPtr, this), false);
  }

  public IdBaseFieldInfo GetMutableBaseFieldInfo() {
    return new IdBaseFieldInfo(jniidengineJNI.IdVideoAuthenticationAnomaly_GetMutableBaseFieldInfo(swigCPtr, this), false);
  }

}
