//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (https://www.swig.org).
// Version 4.1.1
//
// Do not make changes to this file unless you know what you are doing - modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.common {

public enum ImagePixelFormat {
  IPF_G = 0,
  IPF_GA,
  IPF_AG,
  IPF_RGB,
  IPF_BGR,
  IPF_BGRA,
  IPF_ARGB,
  IPF_RGBA
}

}
