/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (https://www.swig.org).
 * Version 4.1.1
 *
 * Do not make changes to this file unless you know what you are doing - modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.smartengines.id;

public final class IdFaceStatus {
  public final static IdFaceStatus IdFaceStatus_NotUsed = new IdFaceStatus("IdFaceStatus_NotUsed");
  public final static IdFaceStatus IdFaceStatus_Success = new IdFaceStatus("IdFaceStatus_Success");
  public final static IdFaceStatus IdFaceStatus_A_FaceNotFound = new IdFaceStatus("IdFaceStatus_A_FaceNotFound");
  public final static IdFaceStatus IdFaceStatus_B_FaceNotFound = new IdFaceStatus("IdFaceStatus_B_FaceNotFound");
  public final static IdFaceStatus IdFaceStatus_FaceNotFound = new IdFaceStatus("IdFaceStatus_FaceNotFound");
  public final static IdFaceStatus IdFaceStatus_NoAccumulatedResult = new IdFaceStatus("IdFaceStatus_NoAccumulatedResult");

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static IdFaceStatus swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + IdFaceStatus.class + " with value " + swigValue);
  }

  private IdFaceStatus(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private IdFaceStatus(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private IdFaceStatus(String swigName, IdFaceStatus swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static IdFaceStatus[] swigValues = { IdFaceStatus_NotUsed, IdFaceStatus_Success, IdFaceStatus_A_FaceNotFound, IdFaceStatus_B_FaceNotFound, IdFaceStatus_FaceNotFound, IdFaceStatus_NoAccumulatedResult };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

